apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: task-manager_notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-upload-service
  template:
    metadata:
      labels:
        app: file-upload-service
    spec:
      containers:
      - name: file-upload-service
        image: task-manager_file-upload-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: file-upload-service
spec:
  selector:
    app: file-upload-service
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP
